// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Acme.Data
{
    public partial class Employee
    {
        public Employee()
        {
            EmployeeProjects = new HashSet<EmployeeProject>();
        }

        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public int GenderId { get; set; }
        public string Email { get; set; }
        public string ReportingLine { get; set; }

        public virtual Gender Gender { get; set; }
        public virtual ICollection<EmployeeProject> EmployeeProjects { get; set; }
    }
}