// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Acme.Data
{
    public partial class Project
    {
        public Project()
        {
            EmployeeProjects = new HashSet<EmployeeProject>();
        }

        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string Status { get; set; }

        public virtual ICollection<EmployeeProject> EmployeeProjects { get; set; }
    }
}