// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Acme.Data
{
    public partial class UserRole
    {
        public int UserRoleId { get; set; }
        public int EmployeeId { get; set; }
        public int RoleId { get; set; }

        public virtual Role Role { get; set; }
    }
}